/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "../../../packages/ui/src/**/*.{js,ts,jsx,tsx}",
    "../../../node_modules/@tremor/**/*.{js,cjs,ts,jsx,tsx}",
    "./node_modules/@tremor/**/*.{js,cjs,ts,jsx,tsx}",
  ],
  safelist: [
    // Tremor classes that might get purged
    'text-tremor-default',
    'rounded-tremor-default',
    'border-tremor-border',
    'bg-tremor-background',
    'bg-tremor-background-muted',
    'divide-tremor-border',
    'shadow-tremor-input',
    'shadow-tremor-dropdown',
    'text-tremor-content',
    'text-tremor-content-subtle',
    'text-tremor-content-strong',
    'text-tremor-brand',
    'text-tremor-brand-inverted',
    'border-tremor-brand',
    'border-tremor-brand-subtle',
    'ring-tremor-ring',
    'ring-tremor-brand-muted',
    'dark:text-dark-tremor-content',
    'dark:text-dark-tremor-content-subtle',
    'dark:text-dark-tremor-content-strong',
    'dark:text-dark-tremor-brand',
    'dark:bg-dark-tremor-background',
    'dark:bg-dark-tremor-background-muted',
    'dark:border-dark-tremor-border',
    'dark:border-dark-tremor-brand',
    'dark:shadow-dark-tremor-input',
    'dark:shadow-dark-tremor-dropdown',
    'dark:divide-dark-tremor-border',
    'dark:ring-dark-tremor-ring',
    'focus:border-tremor-brand-subtle',
    'focus:ring-tremor-brand-muted',
  ],
  theme: {
    extend: {
      colors: {
        // Tremor color mappings
        tremor: {
          brand: 'hsl(var(--primary))',
          'brand-emphasis': 'hsl(var(--primary-hover))',
          'brand-muted': 'hsl(var(--primary-muted))',
          'brand-faint': 'hsl(var(--primary-muted))',
          'brand-subtle': 'hsl(var(--primary-muted))',
          'brand-inverted': 'hsl(var(--foreground))',
          background: 'hsl(var(--surface))',
          'background-muted': 'hsl(var(--surface-raised))',
          border: 'hsl(var(--border))',
          ring: 'hsl(var(--ring))',
          content: 'hsl(var(--text-muted))',
          'content-strong': 'hsl(var(--text))',
          'content-subtle': 'hsl(var(--text-subtle))',
        },
        'dark-tremor': {
          brand: 'hsl(var(--primary))',
          'brand-emphasis': 'hsl(var(--primary-hover))',
          'brand-muted': 'hsl(var(--primary-muted))',
          'brand-faint': 'hsl(var(--primary-muted))',
          'brand-subtle': 'hsl(var(--primary-muted))',
          'brand-inverted': 'hsl(var(--foreground))',
          background: 'hsl(var(--surface))',
          'background-muted': 'hsl(var(--surface-raised))',
          border: 'hsl(var(--border))',
          ring: 'hsl(var(--ring))',
          content: 'hsl(var(--text-muted))',
          'content-strong': 'hsl(var(--text))',
          'content-subtle': 'hsl(var(--text-subtle))',
        },
        // Semantic colors
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        surface: {
          DEFAULT: 'hsl(var(--surface))',
          raised: 'hsl(var(--surface-raised))',
        },
        border: {
          DEFAULT: 'hsl(var(--border))',
          subtle: 'hsl(var(--border-subtle))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          hover: 'hsl(var(--primary-hover))',
          muted: 'hsl(var(--primary-muted))',
        },
        text: {
          DEFAULT: 'hsl(var(--text))',
          muted: 'hsl(var(--text-muted))',
          subtle: 'hsl(var(--text-subtle))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        success: {
          DEFAULT: 'hsl(var(--success))',
          muted: 'hsl(var(--success-muted))',
        },
        warning: {
          DEFAULT: 'hsl(var(--warning))',
          muted: 'hsl(var(--warning-muted))',
        },
        error: {
          DEFAULT: 'hsl(var(--error))',
          muted: 'hsl(var(--error-muted))',
        },
        info: {
          DEFAULT: 'hsl(var(--info))',
          muted: 'hsl(var(--info-muted))',
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'tremor-label': ['0.75rem', { lineHeight: '1rem' }],
        'tremor-default': ['0.875rem', { lineHeight: '1.25rem' }],
        'tremor-title': ['1.125rem', { lineHeight: '1.5rem' }],
        'tremor-metric': ['1.875rem', { lineHeight: '2.25rem' }],
      },
      borderRadius: {
        'tremor-small': 'var(--radius-sm)',
        'tremor-default': 'var(--radius-md)',
        'tremor-full': '9999px',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        'tremor-input': 'var(--shadow-sm)',
        'dark-tremor-input': 'var(--shadow-sm)',
        'tremor-dropdown': 'var(--shadow-md)',
        'dark-tremor-dropdown': 'var(--shadow-md)',
        'tremor-card': 'var(--shadow-md)',
        'dark-tremor-card': 'var(--shadow-md)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      transitionDuration: {
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
      },
    },
  },
  plugins: [],
}
