"""Phase 128 Task 9: resume.py downstream-stub writer must not race with
an active run.

When the orchestrator F-67-deletes a stage manifest before launching its
worker, a parallel resume scan may observe "manifest missing, downstream
manifest present" and write a recovery stub claiming the stage finished
— while the actual worker is still mid-execution. This is the on-disk
inconsistency observed at 21:22:35 on 2026-05-05 in the user's pipeline.

The fix: before writing a downstream-proves-upstream stub, check the
journal for an active run on this stage's group. If one exists, defer.
"""
from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace
from typing import Optional
from unittest.mock import MagicMock, patch

import pytest


@pytest.fixture
def project_with_downstream_only(tmp_path: Path) -> Path:
    """Set up a project where only the DOWNSTREAM stage's manifest exists.
    The upstream stage we'll be checking has its manifest gone (just
    F-67-deleted by the orchestrator)."""
    from prep.services.pipeline.manifest_store import ManifestStore
    from prep.services.pipeline.stages import StageId

    idx = tmp_path / ".sourceprep"
    idx.mkdir()
    store = ManifestStore(idx)
    # Clustering completed in a prior run — needs both manifest AND
    # output file, with finished_at so it isn't flagged "incomplete".
    store.write_provenance(
        StageId.CLUSTERING,
        {
            "format_version": "2.0",
            "stage_id": "clustering",
            "finished_at": "2026-05-04T01:38:15+00:00",
        },
    )
    (idx / "trace_modules.jsonl").write_text('{"id":"m1","files":["a.py"]}\n')
    # Group reasoning manifest missing — about to be regenerated by the
    # active worker. Write a fake trace_group_reasoning.jsonl so any
    # downstream output-check passes.
    (idx / "trace_group_reasoning.jsonl").write_text('{"k":"v"}\n')
    return idx


def _drive_resume(
    idx_dir: Path,
    journal_active_run: Optional[SimpleNamespace],
):
    """Run ResumeStrategy.detect_resume_point with a patched journal."""
    from prep.services.pipeline import resume as resume_mod
    from prep.services.pipeline.stages import StageId
    from prep.services.pipeline_journal import journal as _journal

    fake_project = SimpleNamespace(id="proj-1")

    with patch("prep.services.project_helpers.require_project",
               return_value=fake_project), \
         patch("prep.core.project_registry.project_index_dir",
               return_value=idx_dir), \
         patch.object(_journal, "get_active_run",
                      return_value=journal_active_run):
        result = resume_mod.ResumeStrategy.detect_resume_point(
            "proj-1",
            [StageId.GROUP_REASONING, StageId.CLUSTERING],
            skip_mtime_cascade=True,
        )
    return result


def test_no_stub_when_journal_shows_active_run(
    project_with_downstream_only: Path,
) -> None:
    """An active deep_enrichment run in the journal must defer the stub
    write — recovery returns the missing-stage index, not a CRASH_RECOVERY
    completion."""
    active = SimpleNamespace(
        run_id="run-active", project_id="proj-1",
        group="deep_enrichment", status="running",
    )

    result = _drive_resume(project_with_downstream_only, journal_active_run=active)

    # The function must return 0 (group_reasoning is index 0, missing,
    # not recovered to "done"). No stub manifest written.
    gr_manifest = project_with_downstream_only / "group_reasoning_manifest.json"
    assert not gr_manifest.exists(), (
        "Stub manifest written despite active journal run — race not closed"
    )
    assert result == 0, f"expected resume at GROUP_REASONING (0), got {result}"


def test_stub_written_when_no_active_run(
    project_with_downstream_only: Path,
) -> None:
    """No active run in the journal → existing downstream-proves-upstream
    behavior runs and a stub is written."""
    result = _drive_resume(project_with_downstream_only, journal_active_run=None)

    gr_manifest = project_with_downstream_only / "group_reasoning_manifest.json"
    assert gr_manifest.exists(), (
        "Stub manifest should be written when no active run in journal"
    )
    import json
    data = json.loads(gr_manifest.read_text())
    assert data.get("recovered") is True
    # And resume point advances past the now-recovered stage
    assert result == 2, (
        f"expected resume at end (2) after stub recovery, got {result}"
    )
