[build]
  base    = "websites/apps/docs"
  command = "cd ../../.. && npx turbo run build --filter=@prep/docs"
  publish = "websites/apps/docs/.next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
