"""Phase 125c T3a — per-concept critique prompt for the Validate swarm.

Each Validate worker gets ONE candidate concept (from Generate) plus the
grounding rows whose anchors overlap with the concept's anchors, and
emits a verdict: T3 / T2 / T1 / REJECT.

The verdict drives the final status:
    T3, T2  → 'active'         (auto-accept)
    T1      → 'triage_pending' (queue for human review)
    REJECT  → 'archived'        (hallucination / unsupported)

Disagreement reconciliation between Generate's self-rated tier and
Validate's verdict: Validate wins on downgrades (always); on upgrades
the rule is "meet in middle" (T1 → T3 from Validate becomes T2). See
``apply_verdict`` for the reconciliation logic.

Pure module — no LLM, no I/O. T3b (the runner) wires this into
ThreadPoolExecutor + concept_store updates.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from .concept_synthesizer import (
    SynthesizedConcept,
    VALID_TIERS,
)


VALID_VERDICTS = frozenset({"T1", "T2", "T3", "REJECT"})


@dataclass(frozen=True)
class ValidationVerdict:
    """One Validate worker's output for one candidate concept."""
    verdict: str                # T1 | T2 | T3 | REJECT
    counter_evidence: str
    falsification: str
    rationale: str

    def is_valid(self) -> bool:
        return self.verdict in VALID_VERDICTS


# ── System prompt ───────────────────────────────────────────────────


VALIDATE_SYSTEM_PROMPT = """You are a HOSTILE REVIEWER critiquing one concept
generated by another LLM. Your job is to decide whether the concept's claim is
SUPPORTED by the grounding evidence below it.

Use the named-tier rubric (no floats, no descriptive names — neutral T1/T2/T3
or REJECT). Field order is FIXED — counter_evidence FIRST, tier LAST.

═══════════════════════════════════════════════════════════════════════
TIER RUBRIC
═══════════════════════════════════════════════════════════════════════

T3 — Codified in CI / types / constraint; violations FAIL THE BUILD.
     The grounding contains a specific anchor that enforces the claim
     in CODE (decorator, lint rule, type, runtime check). You can quote
     it. Falsifiable in <5 min via grep or test. T3 requires code-level
     enforcement; doc-only commitments are T2.

T2 — Documented decision OR observable enforcement — EITHER is enough.
     EITHER (a) the claim is stated in an authoritative planning doc
     (ADR / RFC / Phase doc / ARCHITECTURE.md / DESIGN.md / a README
     with heavy in-link count from code), OR (b) the grounding shows
     at least one observable enforcement pattern in code. Doc-only
     anchoring is fine for strategic / positioning concepts ("we don't
     embed UI in client X") — those legitimately live in docs, not in
     enforcement code.

T1 — Pattern observed; no enforcement and no authoritative doc
     anchoring. Speculative reading. The grounding shows the pattern
     but nothing prevents counter-examples. A reader could find a
     counter-example in the same codebase.

REJECT — One of:
  • Claim is NOT supported by grounding (the anchors don't say what
    the concept claims).
  • Claim is a FILE-LEVEL observation, GRAPH FACT, or LIBRARY USE
    statement (belongs in module rationale layer, not concepts).
  • Claim is a BUG DESCRIPTION, AUDIT FINDING, or SECURITY ISSUE
    ("X causes Y bug", "X lacks Y mechanism", "X is attacker-
    controllable", "X creates Y desync") — these belong in the audit
    surface, NOT the concept layer.
  • Claim is a HISTORICAL or META observation about the project's
    documentation or history ("phase docs encode chronological
    evolution", "stage count expanded over time") — these are not
    actionable for an agent working in the code.
  • Claim restates a banned-cliché ("uses async", "modular architecture",
    "follows MVC", "comprehensive", "robust").
  • You cannot quote a verbatim grounding span supporting the claim.

═══════════════════════════════════════════════════════════════════════
PROCESS — for the candidate, in order
═══════════════════════════════════════════════════════════════════════

1. QUOTE: name 1-2 verbatim spans from grounding (file paths or doc
   anchors). If you cannot quote grounding that speaks to the claim,
   verdict=REJECT.

2. COUNTER-EVIDENCE FIRST: list 1-2 files or patterns that would
   WEAKEN the concept if found. Empty counter_evidence and verdict=T3
   is INCONSISTENT — at T3 you must have looked and found the
   counter-example refuted by an enforcement anchor.

3. FALSIFICATION: phrase the assertion so a reviewer with grep can
   disprove it in <5 min. Concrete, code-anchored. If you cannot
   name one, the verdict cannot be above T1.

4. VERDICT — committed AFTER counter_evidence and falsification.
   Default to T1 if grounding is shaky. T3 is RARE — most candidates
   land at T1, T2, or REJECT.

═══════════════════════════════════════════════════════════════════════
OUTPUT SCHEMA — strict JSON object, fields in this EXACT order
═══════════════════════════════════════════════════════════════════════

{
  "counter_evidence": "...",
  "falsification": "...",
  "rationale": "...",
  "verdict": "T3" | "T2" | "T1" | "REJECT"
}

No markdown fences. No prose outside the JSON. No additional fields.
"""


# ── User prompt builder ─────────────────────────────────────────────


def build_validate_user_prompt(
    *,
    candidate: SynthesizedConcept,
    related_rationale: Iterable[dict] = (),
    related_doc_excerpts: Iterable[dict] = (),
    related_audit_findings: Iterable[dict] = (),
) -> str:
    """Build the user prompt for one Validate worker.

    `related_*` arguments contain only the grounding rows whose anchors
    overlap with the candidate's anchors (T3b's runner job to filter).
    """
    parts: list[str] = []
    parts.append("CANDIDATE CONCEPT (from Generate)")
    parts.append("-" * 50)
    parts.append(f"title: {candidate.title}")
    parts.append(f"category: {candidate.category}")
    parts.append(f"self-rated tier (Generate): {candidate.tier}")
    parts.append(f"anchors: {', '.join(candidate.anchors) or '(none)'}")
    if candidate.counter_evidence:
        parts.append(f"counter_evidence (Generate): {candidate.counter_evidence}")
    if candidate.falsification:
        parts.append(f"falsification (Generate): {candidate.falsification}")
    parts.append("")
    parts.append("content:")
    parts.append(candidate.refined_content or candidate.content or "(empty)")
    parts.append("")

    rationale = list(related_rationale)
    if rationale:
        parts.append("GROUNDING — RELATED MODULE RATIONALE")
        parts.append("-" * 50)
        for r in rationale:
            title = (r.get("title") or "")[:80]
            anchors = ", ".join((r.get("anchors") or [])[:3])
            content = (r.get("content") or "")[:300]
            parts.append(f"- {title}")
            parts.append(f"  anchors: {anchors}")
            if content:
                parts.append(f"  content: {content}")
        parts.append("")

    docs = list(related_doc_excerpts)
    if docs:
        parts.append("GROUNDING — RELATED PLANNING DOCS")
        parts.append("-" * 50)
        for d in docs:
            path = d.get("path", "")
            excerpt = (d.get("excerpt") or "")[:1000]
            parts.append(f"## {path}")
            if excerpt:
                parts.append(excerpt)
        parts.append("")

    findings = list(related_audit_findings)
    if findings:
        parts.append("GROUNDING — RELATED AUDIT FINDINGS")
        parts.append("-" * 50)
        for f in findings:
            sev = f.get("severity", "?")
            title = f.get("title", "")
            paths = ", ".join(f.get("file_paths") or [])
            parts.append(f"  [{sev}] {title} — {paths}")
        parts.append("")

    if not (rationale or docs or findings):
        parts.append("GROUNDING — (NONE — anchors don't overlap any indexed grounding)")
        parts.append("(If grounding is empty, verdict is almost certainly T1 or REJECT.)")
        parts.append("")

    parts.append("EMIT JSON OBJECT ONLY. Field order: counter_evidence, "
                 "falsification, rationale, verdict.")
    return "\n".join(parts)


def build_validate_prompt(
    *,
    candidate: SynthesizedConcept,
    related_rationale: Iterable[dict] = (),
    related_doc_excerpts: Iterable[dict] = (),
    related_audit_findings: Iterable[dict] = (),
) -> tuple[str, str]:
    """Return ``(system, user)`` prompts for one Validate worker."""
    return (
        VALIDATE_SYSTEM_PROMPT,
        build_validate_user_prompt(
            candidate=candidate,
            related_rationale=related_rationale,
            related_doc_excerpts=related_doc_excerpts,
            related_audit_findings=related_audit_findings,
        ),
    )


# ── Verdict parsing ─────────────────────────────────────────────────


def parse_verdict_response(text: str) -> ValidationVerdict | None:
    """Parse one Validate worker's JSON output into a ValidationVerdict.

    Returns None if the response is unparsable, empty, or has an
    invalid verdict label. Caller treats None as "validate failed for
    this concept; fall through to gate's default behavior."
    """
    import json
    import re
    if not text or not text.strip():
        return None
    raw = text.strip()
    # Strip optional markdown fence
    fence = re.match(r"^\s*```(?:json)?\s*\n(.+?)\n\s*```\s*$", raw, re.DOTALL)
    if fence:
        raw = fence.group(1)
    try:
        data = json.loads(raw)
    except json.JSONDecodeError:
        return None
    if not isinstance(data, dict):
        return None
    verdict = (data.get("verdict") or "").strip().upper()
    if verdict not in VALID_VERDICTS:
        return None
    return ValidationVerdict(
        verdict=verdict,
        counter_evidence=str(data.get("counter_evidence") or "")[:600],
        falsification=str(data.get("falsification") or "")[:600],
        rationale=str(data.get("rationale") or "")[:1000],
    )


# ── Disagreement reconciliation ─────────────────────────────────────


def reconcile_tier(
    generate_tier: str,
    validate_verdict: str,
) -> tuple[str, str]:
    """Combine Generate's self-rated tier with Validate's verdict.

    Rules:
      - REJECT always wins (any tier from Generate → REJECT).
      - Validate wins on downgrades (always — strict reviewer).
      - On upgrades (Generate said T1, Validate said T3): "meet in middle"
        (final = T2). The pattern surfaces a fact for human re-look without
        leaping directly from speculative to load-bearing.
      - Tier-distance ≥ 2 in the upgrade direction is the only place
        the meet-in-middle rule fires; tier-distance 1 upgrade is
        accepted as-is.

    Returns ``(final_tier, final_status)`` where status is one of
    'active' / 'triage_pending' / 'archived' per the verdict map.
    """
    if validate_verdict == "REJECT":
        return ("REJECT", "archived")

    tier_rank = {"T1": 1, "T2": 2, "T3": 3}
    gen_r = tier_rank.get(generate_tier, 0)
    val_r = tier_rank.get(validate_verdict, 0)

    if val_r <= gen_r:
        # Downgrade or equal → Validate's tier wins.
        final_tier = validate_verdict
    elif val_r - gen_r >= 2:
        # Big upgrade (T1 → T3) → meet in middle.
        final_tier = "T2"
    else:
        # Small upgrade (T1 → T2 or T2 → T3) → accept Validate's call.
        final_tier = validate_verdict

    if final_tier in ("T2", "T3"):
        return (final_tier, "active")
    if final_tier == "T1":
        return (final_tier, "triage_pending")
    # Defensive — should be unreachable given the verdict whitelist
    return (final_tier, "archived")
