from __future__ import annotations

import os
from collections import Counter
from pathlib import Path
from typing import Any, Dict, Iterator, List, Sequence, Set, Tuple

# Directories Prep itself writes. Indexing any of these creates a feedback
# loop in which the LLM reasons about Prep's own state instead of the user's
# code. Every new writer must register here; DEFAULT_EXCLUDE_DIR_NAMES derives
# from this set so the universal default exclude list updates automatically.
PREP_OUTPUT_DIRS: Set[str] = {
    ".sourceprep",   # per-project index (embedded mode)
    ".runprep",      # legacy per-project index (pre-SourcePrep rename)
    "prep_data",   # daemon-wide store (SQLite + telemetry + ui_config)
}

# Glob patterns for files Prep or AI agents write at project root.
# DEFAULT_EXCLUDE_FILE_GLOBS unpacks this tuple so additions propagate.
PREP_OUTPUT_FILE_GLOBS: Sequence[str] = (
    # Prep-generated
    "**/AGENTS.md",
    # Claude Code
    "**/CLAUDE.md",
    # Cursor
    "**/.cursor/rules/*.mdc",
    "**/.cursorrules",
    # Windsurf
    "**/.windsurfrules",
    "**/.windsurf/rules/*.md",
    # GitHub Copilot
    "**/.github/copilot-instructions.md",
    # Gemini CLI
    "**/GEMINI.md",
    # Cline / Roo
    "**/.clinerules",
    "**/.roorules",
    # Qwen Code
    "**/.qwencoderules",
)

DEFAULT_EXCLUDE_DIR_NAMES: Set[str] = PREP_OUTPUT_DIRS | {
    # VCS
    ".git",
    # Python dep/build dirs
    "node_modules",
    "__pycache__",
    ".venv",
    "venv",
    "fresh_venv",
    "env",
    ".env",
    ".tox",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "htmlcov",
    ".coverage",
    "coverage",
    # Generic build output
    "dist",
    "build",
    "target",
    "out",
    # Frontend build/meta dirs
    "storybook-static",
    ".next",
    ".turbo",
    ".vercel",
    ".parcel-cache",
    ".svelte-kit",
    ".astro",
    ".nuxt",
    ".cache",
    # iOS / mobile dependency dirs
    "Pods",
    "Carthage",
    ".gradle",
    "DerivedData",
    # Cross-ecosystem vendor/dependency dirs
    "vendor",
    "bundle",
    ".bundle",
    "bower_components",
    # AI tool config directories (contain instruction files, not source code).
    # These are NOT source — the trace pipeline silently ignores them. They
    # ARE fed to the concept synthesizer (Phase 125c) as planning grounding
    # via src/prep/core/docs_grounding.py, which has its own walker with
    # ALLOWED_DOT_DIRS set so these dirs are visible to that path only.
    ".claude",
    ".cursor",
    ".windsurf",
    ".continue",
    ".cody",
    ".aider",
    ".agents",
}

# Files generated by Prep or AI tools that should be excluded from trace
# indexing. These are instruction/config files for AI coding assistants —
# agents already have direct access to them, and tracing them wastes LLM
# tokens on meta-content that doesn't describe the codebase architecture.
DEFAULT_EXCLUDE_FILE_NAMES: Set[str] = {
    "AGENTS.md",
    "CLAUDE.md",
    "GEMINI.md",
    ".cursorrules",
    ".cursorignore",
    ".windsurfrules",
    ".clinerules",
    ".roorules",
    ".clineignore",
    ".qwencoderules",
}

# Glob patterns for files to exclude from trace indexing.
# Starts with PREP_OUTPUT_FILE_GLOBS so any new output registered there
# flows through automatically. Additional entries target build artifacts
# that look like source files to the walker (TypeScript declarations,
# minified bundles, source maps) but carry no structural value for the LLM.
DEFAULT_EXCLUDE_FILE_GLOBS: Sequence[str] = (
    *PREP_OUTPUT_FILE_GLOBS,
    # Build artifacts that look like source
    "**/*.d.ts",       # TypeScript declaration files — generated
    "**/*.min.js",
    "**/*.min.css",
    "**/*.map",        # source maps
)

DOC_DIR_NAMES: Set[str] = {
    "docs",
    "doc",
    "documentation",
    "design",
    "spec",
    "specs",
    "architecture",
    "arch",
    "adr",
    "adrs",
    "decisions",
    "decision",
    "rfc",
    "rfcs",
}

TEST_DIR_NAMES: Set[str] = {
    "test",
    "tests",
    "__tests__",
    "testing",
}

CODE_DIR_NAMES: Set[str] = {
    "src",
    "lib",
    "app",
    "apps",
    "packages",
    "pkg",
    "server",
    "client",
    "ui",
    "frontend",
    "backend",
    "cmd",
}

DEFAULT_ROLE_WEIGHTS: Dict[str, float] = {
    "code": 1.0,
    "docs": 0.85,
    "tests": 0.95,
    "other": 0.80,
}

MARKER_FILES: Sequence[str] = (
    "pyproject.toml",
    "requirements.txt",
    "setup.py",
    "package.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    "go.mod",
    "Cargo.toml",
    "pom.xml",
    "build.gradle",
    "Makefile",
)

# ── Stack Presets (Fast Scan) ────────────────────────────────────

STACK_PRESETS: Dict[str, List[str]] = {
    "Web (JS/TS)": ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx", "**/*.html", "**/*.css", "**/*.json"],
    "Python": ["**/*.py", "**/*.ipynb"],
    "iOS (Swift/ObjC)": ["**/*.swift", "**/*.h", "**/*.m", "**/*.mm"],
    "Rust": ["**/*.rs", "**/*.toml"],
    "Go": ["**/*.go", "**/*.mod"],
    "Java/Kotlin": ["**/*.java", "**/*.kt", "**/*.kts", "**/*.gradle"],
    "C/C++": ["**/*.c", "**/*.cpp", "**/*.h", "**/*.hpp", "**/*.cc"],
    "C#": ["**/*.cs"],
    "Ruby": ["**/*.rb"],
    "PHP": ["**/*.php"],
    "Shell": ["**/*.sh", "**/*.bash", "**/*.zsh"],
    "Dart/Flutter": ["**/*.dart"],
    "Scala": ["**/*.scala", "**/*.sc"],
    "Lua": ["**/*.lua"],
    "Zig": ["**/*.zig"],
    "Elixir": ["**/*.ex", "**/*.exs"],
    "Configuration": ["**/*.yaml", "**/*.yml", "**/*.json", "**/*.toml", "**/*.xml", "**/*.ini", "**/*.env"],
    "Documentation": ["**/*.md", "**/*.markdown", "**/*.txt"],
}

# Map extension to preset keys
EXT_TO_PRESET: Dict[str, str] = {
    ".js": "Web (JS/TS)", ".jsx": "Web (JS/TS)", ".ts": "Web (JS/TS)", ".tsx": "Web (JS/TS)", ".html": "Web (JS/TS)", ".css": "Web (JS/TS)",
    ".py": "Python", ".ipynb": "Python",
    ".swift": "iOS (Swift/ObjC)", ".m": "iOS (Swift/ObjC)", ".mm": "iOS (Swift/ObjC)",
    ".rs": "Rust",
    ".go": "Go",
    ".java": "Java/Kotlin", ".kt": "Java/Kotlin",
    ".c": "C/C++", ".cpp": "C/C++", ".h": "C/C++", ".hpp": "C/C++", ".cc": "C/C++",
    ".cs": "C#",
    ".rb": "Ruby",
    ".php": "PHP",
    ".sh": "Shell", ".bash": "Shell", ".zsh": "Shell",
    ".dart": "Dart/Flutter",
    ".scala": "Scala", ".sc": "Scala",
    ".lua": "Lua",
    ".zig": "Zig",
    ".ex": "Elixir", ".exs": "Elixir",
    ".yaml": "Configuration", ".yml": "Configuration", ".json": "Configuration", ".xml": "Configuration", ".toml": "Configuration",
    ".md": "Documentation",
}

def scan_for_presets(root: Path) -> List[str]:
    """
    Quickly scan the project root for file extensions to determine active presets.
    Skips common heavy directories to be fast.
    """
    detected_presets = set()
    # Limit depth and directories to avoid slow scans in huge monorepos
    ignore_dirs = DEFAULT_EXCLUDE_DIR_NAMES | {"vendor", ".idea", ".vscode"}
    
    try:
        # We'll just walk up to 3 levels deep for speed, or until we find enough evidence
        for dirpath, dirnames, filenames in os.walk(str(root)):
            # Prune ignored dirs
            dirnames[:] = [d for d in dirnames if d not in ignore_dirs and not d.startswith(".")]
            
            for f in filenames:
                ext = Path(f).suffix.lower()
                if ext in EXT_TO_PRESET:
                    detected_presets.add(EXT_TO_PRESET[ext])
            
            pass
    except Exception:
        pass
        
    return list(detected_presets)


CODE_EXTS: Set[str] = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".go",
    ".rs",
    ".java",
    ".kt",
    ".kts",
    ".c",
    ".h",
    ".cc",
    ".cpp",
    ".hpp",
    ".cs",
    ".swift",
    ".rb",
    ".php",
    ".dart",
    ".scala",
    ".sc",
    ".sh",
    ".bash",
    ".zsh",
    ".lua",
    ".zig",
    ".ex",
    ".exs",
}

DOC_EXTS: Set[str] = {
    ".md",
    ".markdown",
    ".rst",
    ".txt",
}


def classify_rel_path(rel_path: str) -> str:
    p = rel_path.replace("\\", "/").lower()
    parts = [x for x in p.split("/") if x]

    if any(part in TEST_DIR_NAMES for part in parts):
        return "tests"

    ext = Path(p).suffix
    if ext in DOC_EXTS or any(part in DOC_DIR_NAMES for part in parts):
        return "docs"

    if ext in CODE_EXTS or any(part in CODE_DIR_NAMES for part in parts):
        return "code"

    return "other"


def classify_dir_name(name: str) -> Tuple[str, float]:
    n = name.lower().strip("/")
    if n in DOC_DIR_NAMES:
        return "docs", 0.9
    if n in TEST_DIR_NAMES:
        return "tests", 0.9
    if n in CODE_DIR_NAMES:
        return "code", 0.9
    return "other", 0.5


def _iter_repo_files(repo_root: Path, max_depth: int, max_files: int) -> Iterator[Path]:
    seen = 0
    for root, dirs, files in os.walk(repo_root, topdown=True):
        rel_dir = Path(root).resolve().relative_to(repo_root)
        depth = len(rel_dir.parts)

        dirs[:] = [
            d
            for d in dirs
            if d not in DEFAULT_EXCLUDE_DIR_NAMES and not d.startswith(".")
        ]

        if depth >= max_depth:
            dirs[:] = []

        for fn in files:
            if fn.startswith("."):
                continue
            yield Path(root) / fn
            seen += 1
            if seen >= max_files:
                return


def profile_repo(repo_root: Path, max_depth: int = 4, max_files: int = 5000) -> Dict[str, Any]:
    repo_root = Path(repo_root).resolve()

    top_level_dirs: List[str] = []
    if repo_root.exists():
        for child in repo_root.iterdir():
            if child.is_dir() and not child.name.startswith(".") and child.name not in DEFAULT_EXCLUDE_DIR_NAMES:
                top_level_dirs.append(child.name)
    top_level_dirs = sorted(top_level_dirs)

    marker_files = [name for name in MARKER_FILES if (repo_root / name).exists()]

    ext_counts: Counter[str] = Counter()
    for p in _iter_repo_files(repo_root, max_depth=max_depth, max_files=max_files):
        ext = p.suffix.lower()
        if ext:
            ext_counts[ext] += 1

    detected_languages: Set[str] = set()

    if "pyproject.toml" in marker_files or "requirements.txt" in marker_files or ext_counts.get(".py", 0) > 0:
        detected_languages.add("python")

    if "package.json" in marker_files or ext_counts.get(".ts", 0) > 0 or ext_counts.get(".tsx", 0) > 0:
        detected_languages.add("typescript")
    elif ext_counts.get(".js", 0) > 0 or ext_counts.get(".jsx", 0) > 0:
        detected_languages.add("javascript")

    if "go.mod" in marker_files or ext_counts.get(".go", 0) > 0:
        detected_languages.add("go")

    if "Cargo.toml" in marker_files or ext_counts.get(".rs", 0) > 0:
        detected_languages.add("rust")

    if "pom.xml" in marker_files or "build.gradle" in marker_files or ext_counts.get(".java", 0) > 0:
        detected_languages.add("java")

    if ext_counts.get(".kt", 0) > 0 or ext_counts.get(".kts", 0) > 0:
        detected_languages.add("kotlin")

    if "Gemfile" in marker_files or ext_counts.get(".rb", 0) > 0:
        detected_languages.add("ruby")

    if "composer.json" in marker_files or ext_counts.get(".php", 0) > 0:
        detected_languages.add("php")

    if ext_counts.get(".swift", 0) > 0:
        detected_languages.add("swift")

    if ext_counts.get(".c", 0) > 0 or ext_counts.get(".cpp", 0) > 0 or ext_counts.get(".cc", 0) > 0 or ext_counts.get(".h", 0) > 0:
        detected_languages.add("c")

    if ext_counts.get(".cs", 0) > 0:
        detected_languages.add("csharp")

    if ext_counts.get(".dart", 0) > 0:
        detected_languages.add("dart")

    if ext_counts.get(".scala", 0) > 0 or ext_counts.get(".sc", 0) > 0:
        detected_languages.add("scala")

    if ext_counts.get(".sh", 0) > 0 or ext_counts.get(".bash", 0) > 0:
        detected_languages.add("shell")

    if ext_counts.get(".lua", 0) > 0:
        detected_languages.add("lua")

    if ext_counts.get(".zig", 0) > 0:
        detected_languages.add("zig")

    if ext_counts.get(".ex", 0) > 0 or ext_counts.get(".exs", 0) > 0:
        detected_languages.add("elixir")

    include_globs: List[str] = []

    if ext_counts.get(".md", 0) > 0 or (repo_root / "README.md").exists() or (repo_root / "docs").exists():
        include_globs.extend(["**/*.md", "**/*.markdown"])

    if ext_counts.get(".rst", 0) > 0:
        include_globs.append("**/*.rst")

    if "python" in detected_languages:
        include_globs.append("**/*.py")

    if "typescript" in detected_languages:
        # TS projects nearly always have .js config files (jest.config.js,
        # next.config.js, etc.) and mixed TS/JS source. Generated bundle .js
        # lives under build/dist/storybook-static/.next, all in the exclude
        # list. Include both dialects whenever TS is detected.
        include_globs.extend(["**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"])
    elif "javascript" in detected_languages:
        include_globs.extend(["**/*.js", "**/*.jsx"])

    if "go" in detected_languages:
        include_globs.append("**/*.go")

    if "rust" in detected_languages:
        include_globs.append("**/*.rs")

    if "java" in detected_languages:
        include_globs.extend(["**/*.java", "**/*.kt", "**/*.kts"])

    if "kotlin" in detected_languages and "java" not in detected_languages:
        include_globs.extend(["**/*.kt", "**/*.kts"])

    if "ruby" in detected_languages:
        include_globs.append("**/*.rb")

    if "php" in detected_languages:
        include_globs.append("**/*.php")

    if "swift" in detected_languages:
        include_globs.append("**/*.swift")

    if "c" in detected_languages:
        include_globs.extend(["**/*.c", "**/*.cpp", "**/*.cc", "**/*.h", "**/*.hpp"])

    if "csharp" in detected_languages:
        include_globs.append("**/*.cs")

    if "dart" in detected_languages:
        include_globs.append("**/*.dart")

    if "scala" in detected_languages:
        include_globs.extend(["**/*.scala", "**/*.sc"])

    if "shell" in detected_languages:
        include_globs.extend(["**/*.sh", "**/*.bash", "**/*.zsh"])

    if "lua" in detected_languages:
        include_globs.append("**/*.lua")

    if "zig" in detected_languages:
        include_globs.append("**/*.zig")

    if "elixir" in detected_languages:
        include_globs.extend(["**/*.ex", "**/*.exs"])

    include_globs = sorted(set(include_globs))

    # Base excludes from our comprehensive directory list
    exclude_globs: List[str] = [f"**/{d}/**" for d in sorted(DEFAULT_EXCLUDE_DIR_NAMES)]
    # Build-artifact / AI-tool file globs registered in DEFAULT_EXCLUDE_FILE_GLOBS
    exclude_globs.extend(DEFAULT_EXCLUDE_FILE_GLOBS)
    # Broad exclusion for dotfiles/dotdirs
    exclude_globs.append("**/.*")
    # Legacy-standard single-file patterns
    exclude_globs.extend([
        "**/*.lock",
        "**/*.log",
        "**/.DS_Store",
    ])
    exclude_globs = sorted(set(exclude_globs))

    path_roles: List[Dict[str, Any]] = []
    for d in top_level_dirs:
        role, confidence = classify_dir_name(d)
        path_roles.append({"path": d + "/**", "role": role, "confidence": confidence})

    return {
        "repo_root": str(repo_root),
        "top_level_dirs": top_level_dirs,
        "marker_files": marker_files,
        "extension_counts": dict(ext_counts.most_common(30)),
        "detected_languages": sorted(detected_languages),
        "path_roles": path_roles,
        "recommended": {
            "include_globs": include_globs,
            "exclude_globs": exclude_globs,
            "role_weights": dict(DEFAULT_ROLE_WEIGHTS),
        },
    }
