"""
Stage Manifest — Enhanced metadata for pipeline stages.

Each pipeline stage writes a manifest file with:
- Model provenance (which LLM/embedding model was used)
- Timing information (start, end, elapsed)
- Quality metrics (success rate, confidence scores)
- File provenance (input/output hashes)
- Performance metrics (throughput)

This enables:
- Data provenance tracking ("This was generated by qwen3:14b on 2026-03-11")
- Quality assessment ("Average confidence: 0.87")
- Debugging ("Why did this fail?" → check manifest for errors)
- Model comparison ("Model A: 0.87 avg confidence, Model B: 0.92")
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class StageManifest:
    """Enhanced manifest for a pipeline stage.
    
    Written by each stage worker after completion to provide full
    provenance and quality tracking.
    """
    format_version: str = "2.0"
    stage_id: str = ""
    run_id: Optional[str] = None
    project_id: Optional[str] = None
    
    # Provenance
    prep_version: str = ""
    engine_version: Optional[str] = None
    engine_backend: str = "python"  # "python" | "rust"
    
    # Model Info (for LLM stages)
    model: Optional[Dict[str, Any]] = None
    # {
    #   "task_id": "fast_catalogue",
    #   "provider": "ollama",
    #   "endpoint_id": "local-ollama",
    #   "model_name": "qwen3:14b",
    #   "model_variant": "q8_0",
    #   "batch_profile": "off",
    #   "concurrency": 4
    # }
    
    # Embedding Model Info (for knowledge index)
    embedding_model: Optional[Dict[str, Any]] = None
    # {
    #   "provider": "native",
    #   "model_name": "nomic-embed-text-v1.5",
    #   "dimensions": 768
    # }
    
    # Timing
    started_at: Optional[str] = None  # ISO timestamp
    finished_at: Optional[str] = None
    elapsed_seconds: Optional[float] = None
    
    # Quality Metrics
    quality: Optional[Dict[str, Any]] = None
    # {
    #   "total_items": 247,
    #   "processed": 245,
    #   "skipped": 2,
    #   "failed": 0,
    #   "success_rate": 0.992,
    #   "avg_confidence": 0.87,
    #   "min_confidence": 0.45,
    #   "max_confidence": 0.98,
    #   "parse_errors": 0
    # }
    
    # File Provenance
    input_files: Optional[Dict[str, Dict[str, Any]]] = None
    # filename → {size_bytes, hash, item_count}
    
    output_files: Optional[Dict[str, Dict[str, Any]]] = None
    # filename → {size_bytes, hash, item_count}
    
    # Performance
    throughput: Optional[Dict[str, float]] = None
    # {items_per_second, bytes_per_second}
    
    # Errors (if any)
    errors: Optional[List[Dict[str, str]]] = None
    # [{node_id, error, detail}]

    # F-66: Incremental baseline — items that existed before this run.
    # Used by the dashboard to render 2-tone progress bars that persist
    # across page refresh and daemon restart.
    incremental_baseline: Optional[int] = None

    # Recovery markers — set when a manifest is reconstructed rather than
    # written by a real stage run. Surfaces in the dashboard so users can
    # distinguish "this stage ran and recorded provenance" from "the
    # manifest was synthesized after data was resurrected from a backup /
    # inferred from downstream success".
    restored: Optional[bool] = None           # selfheal stub
    source: Optional[str] = None              # e.g. "selfheal"
    backup_type: Optional[str] = None         # e.g. "run_checkpoint", "golden", "branch_snapshot"
    restored_at: Optional[str] = None         # ISO timestamp of resurrection
    recovered: Optional[bool] = None          # crash-recovery placeholder
    recovery_note: Optional[str] = None       # human-readable explanation

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dict for JSON output."""
        d: Dict[str, Any] = {
            "format_version": self.format_version,
            "stage_id": self.stage_id,
        }
        
        if self.run_id:
            d["run_id"] = self.run_id
        if self.project_id:
            d["project_id"] = self.project_id
        
        # Provenance
        if self.prep_version:
            d["prep_version"] = self.prep_version
        if self.engine_version:
            d["engine_version"] = self.engine_version
        if self.engine_backend:
            d["engine_backend"] = self.engine_backend
        
        # Model info
        if self.model:
            d["model"] = self.model
        if self.embedding_model:
            d["embedding_model"] = self.embedding_model
        
        # Timing
        if self.started_at:
            d["started_at"] = self.started_at
        if self.finished_at:
            d["finished_at"] = self.finished_at
        if self.elapsed_seconds is not None:
            d["elapsed_seconds"] = round(self.elapsed_seconds, 2)
        
        # Quality
        if self.quality:
            d["quality"] = self.quality
        
        # File provenance
        if self.input_files:
            d["input_files"] = self.input_files
        if self.output_files:
            d["output_files"] = self.output_files
        
        # Performance
        if self.throughput:
            d["throughput"] = self.throughput
        
        # Errors
        if self.errors:
            d["errors"] = self.errors

        # F-66: Incremental baseline
        if self.incremental_baseline is not None and self.incremental_baseline > 0:
            d["incremental_baseline"] = self.incremental_baseline

        # Recovery markers
        if self.restored is not None:
            d["restored"] = self.restored
        if self.source:
            d["source"] = self.source
        if self.backup_type:
            d["backup_type"] = self.backup_type
        if self.restored_at:
            d["restored_at"] = self.restored_at
        if self.recovered is not None:
            d["recovered"] = self.recovered
        if self.recovery_note:
            d["recovery_note"] = self.recovery_note

        return d
    
    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "StageManifest":
        """Deserialize from dict."""
        return cls(
            format_version=d.get("format_version", "2.0"),
            stage_id=d.get("stage_id", ""),
            run_id=d.get("run_id"),
            project_id=d.get("project_id"),
            prep_version=d.get("prep_version", ""),
            engine_version=d.get("engine_version"),
            engine_backend=d.get("engine_backend", "python"),
            model=d.get("model"),
            embedding_model=d.get("embedding_model"),
            started_at=d.get("started_at"),
            finished_at=d.get("finished_at"),
            elapsed_seconds=d.get("elapsed_seconds"),
            quality=d.get("quality"),
            input_files=d.get("input_files"),
            output_files=d.get("output_files"),
            throughput=d.get("throughput"),
            errors=d.get("errors"),
            incremental_baseline=d.get("incremental_baseline"),
            restored=d.get("restored"),
            source=d.get("source"),
            backup_type=d.get("backup_type"),
            restored_at=d.get("restored_at"),
            recovered=d.get("recovered"),
            recovery_note=d.get("recovery_note"),
        )


def create_stage_manifest(
    stage_id: str,
    run_id: Optional[str] = None,
    project_id: Optional[str] = None,
) -> StageManifest:
    """Create a new StageManifest with basic provenance info.
    
    Call this at the start of a stage, then populate timing/quality/etc.
    as the stage executes.
    """
    from prep.core.provenance import get_codrag_version, get_engine_version, get_engine_backend
    
    return StageManifest(
        format_version="2.0",
        stage_id=stage_id,
        run_id=run_id,
        project_id=project_id,
        prep_version=get_codrag_version(),
        engine_version=get_engine_version(),
        engine_backend=get_engine_backend(),
        started_at=datetime.now(timezone.utc).isoformat(),
    )


def save_stage_manifest(manifest: StageManifest, path: Path) -> None:
    """Write a StageManifest to a JSON file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(manifest.to_dict(), f, indent=2, ensure_ascii=False)


def load_stage_manifest(path: Path) -> Optional[StageManifest]:
    """Load a StageManifest from a JSON file.
    
    Returns None if file doesn't exist or is invalid.
    """
    if not path.exists():
        return None
    
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return StageManifest.from_dict(data)
    except Exception:
        return None
