// Stryker mutation testing config.
//
// What this does: for each "mutant" (a small code change like `>` → `>=`,
// `&&` → `||`, `return X` → `return null`) generated by Stryker against
// the files listed in `mutate`, re-run our vitest suite and check if any
// test fails. A "killed" mutant means our tests caught the change
// (good — the contract is pinned). A "survived" mutant means our tests
// passed even with the regression (bad — the test claims coverage it
// doesn't actually have).
//
// This is the systematic version of the manual /tmp-backup mutations
// I've been doing during PR-D through PR-H scrutiny. PR-H/2 shipped a
// fixture with vacuous coverage for 2 of 5 deep stages — mutation
// testing would have surfaced that without 78 verifier subagents.
//
// Local-dev only today; no CI gate. Run:
//   npm --workspace=packages/ui run mutate
// Single-file focus:
//   npm --workspace=packages/ui run mutate -- --mutate "src/components/trace/freezeGreen.ts"

/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
export default {
  testRunner: 'vitest',
  reporters: ['html', 'clear-text', 'progress'],

  // Start narrow: the two files we want to systematically pin behavior on.
  // Expanding to all src/ would be 30-60 min; this scope is ~5-10 min and
  // covers the Phase 145 §9.3 #28/#29/#30 contract surface.
  mutate: [
    'src/components/trace/freezeGreen.ts',
    'src/components/trace/GraphEnrichmentPipeline.tsx',
  ],

  // No thresholds enforced — initial baseline, not a gate. Once we
  // know the score for these files we can set realistic thresholds
  // and treat regressions as failures.
  thresholds: { high: 80, low: 60, break: null },

  // Vitest config inherits from packages/ui/vitest.config.ts.
  // Stryker spawns its own vitest workers; our happy-dom env is reused.
  vitest: {
    configFile: 'vitest.config.ts',
  },

  // HTML report lands in reports/mutation/mutation.html — open after each
  // run. Survived mutants tell you where to add test coverage.
  htmlReporter: { fileName: 'reports/mutation/mutation.html' },

  // Cleanup: keep the temp directory for diagnosis when mutants behave
  // unexpectedly (e.g. all-survived = vitest config issue, not real gap).
  cleanTempDir: true,
};
