"""
Goalposts data models for CoDRAG (Phase 57).

Core data structures for the forward-looking AI planning system.
Goalposts analyzes the existing codebase epistemology and proposes
actionable milestones, surfaces design questions, and tracks user decisions.
"""
from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional


# ── Proposal categories ──────────────────────────────────────────────

VALID_CATEGORIES = frozenset({
    "architecture",   # Structural improvements (decompose, refactor)
    "security",       # Auth, secrets, input validation, hardening
    "feature",        # New user-facing functionality
    "tech_debt",      # Known debt, stale code, fixup
    "research",       # Ambiguity that needs investigation before acting
})

VALID_STATES = frozenset({"proposed", "approved", "dismissed", "refined"})


# ── Core models ──────────────────────────────────────────────────────

@dataclass
class GoalpostTask:
    """A concrete sub-task within a goalpost proposal."""
    description: str
    file_paths: List[str] = field(default_factory=list)    # relevant files
    effort: str = "small"                                   # small | medium | large

    def to_dict(self) -> Dict[str, Any]:
        return {
            "description": self.description,
            "file_paths": self.file_paths,
            "effort": self.effort,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "GoalpostTask":
        return cls(
            description=d.get("description", ""),
            file_paths=d.get("file_paths", []),
            effort=d.get("effort", "small"),
        )


@dataclass
class GoalpostProposal:
    """A proposed milestone/goalpost generated by the LLM planner."""
    id: str = ""
    title: str = ""
    rationale: str = ""                 # Why this matters now
    category: str = "feature"           # architecture | security | feature | tech_debt | research
    state: str = "proposed"             # proposed | approved | dismissed | refined
    tasks: List[GoalpostTask] = field(default_factory=list)
    priority: str = "P2"               # P0-P4
    created_at: str = ""
    decided_at: str = ""               # When user approved/dismissed

    def __post_init__(self):
        if not self.id:
            self.id = f"GP-{uuid.uuid4().hex[:8]}"
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "title": self.title,
            "rationale": self.rationale,
            "category": self.category,
            "state": self.state,
            "tasks": [t.to_dict() for t in self.tasks],
            "priority": self.priority,
            "created_at": self.created_at,
            "decided_at": self.decided_at,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "GoalpostProposal":
        return cls(
            id=d.get("id", ""),
            title=d.get("title", ""),
            rationale=d.get("rationale", ""),
            category=d.get("category", "feature"),
            state=d.get("state", "proposed"),
            tasks=[GoalpostTask.from_dict(t) for t in d.get("tasks", [])],
            priority=d.get("priority", "P2"),
            created_at=d.get("created_at", ""),
            decided_at=d.get("decided_at", ""),
        )


@dataclass
class GoalpostQuestion:
    """A design question surfaced by the LLM that needs user input."""
    id: str = ""
    question: str = ""
    context: str = ""                   # Why the LLM is asking this
    category: str = "feature"
    answered: bool = False
    answer: str = ""
    created_at: str = ""

    def __post_init__(self):
        if not self.id:
            self.id = f"GQ-{uuid.uuid4().hex[:8]}"
        if not self.created_at:
            self.created_at = datetime.now(timezone.utc).isoformat()

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "question": self.question,
            "context": self.context,
            "category": self.category,
            "answered": self.answered,
            "answer": self.answer,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "GoalpostQuestion":
        return cls(
            id=d.get("id", ""),
            question=d.get("question", ""),
            context=d.get("context", ""),
            category=d.get("category", "feature"),
            answered=d.get("answered", False),
            answer=d.get("answer", ""),
            created_at=d.get("created_at", ""),
        )


@dataclass
class GoalpostsState:
    """Complete persisted state for a project's goalposts."""
    product_intent: str = ""            # User's description of their product direction
    proposals: List[GoalpostProposal] = field(default_factory=list)
    questions: List[GoalpostQuestion] = field(default_factory=list)
    last_generated_at: str = ""
    model_used: str = ""
    generation_tokens: int = 0
    generation_duration_ms: float = 0.0
    version: int = 1                     # Schema version for future migration

    @property
    def active_proposals(self) -> List[GoalpostProposal]:
        return [p for p in self.proposals if p.state == "proposed"]

    @property
    def approved_proposals(self) -> List[GoalpostProposal]:
        return [p for p in self.proposals if p.state == "approved"]

    @property
    def unanswered_questions(self) -> List[GoalpostQuestion]:
        return [q for q in self.questions if not q.answered]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "version": self.version,
            "product_intent": self.product_intent,
            "proposals": [p.to_dict() for p in self.proposals],
            "questions": [q.to_dict() for q in self.questions],
            "last_generated_at": self.last_generated_at,
            "model_used": self.model_used,
            "generation_tokens": self.generation_tokens,
            "generation_duration_ms": round(self.generation_duration_ms, 1),
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "GoalpostsState":
        return cls(
            product_intent=d.get("product_intent", ""),
            proposals=[GoalpostProposal.from_dict(p) for p in d.get("proposals", [])],
            questions=[GoalpostQuestion.from_dict(q) for q in d.get("questions", [])],
            last_generated_at=d.get("last_generated_at", ""),
            model_used=d.get("model_used", ""),
            generation_tokens=d.get("generation_tokens", 0),
            generation_duration_ms=d.get("generation_duration_ms", 0.0),
            version=d.get("version", 1),
        )


# ── Persistence ──────────────────────────────────────────────────────

GOALPOSTS_FILENAME = "goalposts.json"


def load_goalposts(index_dir: Path) -> GoalpostsState:
    """Load goalposts state from the index directory."""
    path = Path(index_dir) / GOALPOSTS_FILENAME
    if not path.exists():
        return GoalpostsState()
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return GoalpostsState.from_dict(data)
    except (json.JSONDecodeError, KeyError, TypeError):
        return GoalpostsState()


def save_goalposts(state: GoalpostsState, index_dir: Path) -> None:
    """Write goalposts state to the index directory."""
    path = Path(index_dir) / GOALPOSTS_FILENAME
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(state.to_dict(), indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
