import {
  AlertTriangle,
  BookOpen,
  Brain,
  ClipboardCheck,
  Coins,
  Compass,
  Database,
  FileCode2,
  Flame,
  FolderTree,
  GitBranch,
  Hammer,
  HeartPulse,
  Lightbulb,
  Map,
  Search,
  Settings2,
  FileText,
  SlidersHorizontal,
  List,
  Target,
  Terminal,
  Bot,
  Network,
} from 'lucide-react';
import type { PanelDefinition } from '../types/layout';

/**
 * Registry of all available dashboard panels
 * Used by PanelPicker and for rendering the modular layout
 */
export const PANEL_REGISTRY: PanelDefinition[] = [
  {
    id: 'log-console',
    title: 'Process Logs',
    description: 'Real-time logs from the SourcePrep daemon.',
    icon: Terminal,
    minHeight: 3,
    defaultHeight: 5,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#key-panels',
    noPadding: true,
  },
  {
    id: 'usage-guide',
    title: 'Quick Start',
    description: 'MCP tool names and usage examples to get started with your AI assistant.',
    icon: BookOpen,
    minHeight: 3,
    defaultHeight: 6,
    category: 'status',
    closeable: true,
    resizable: false,
    docsUrl: 'https://docs.sourceprep.io',
  },
  {
    id: 'mcp-snippet',
    title: 'MCP Setup Snippet',
    description: 'Copy-paste MCP config JSON for any IDE or CLI — picker-driven, with the absolute `prep` command baked in.',
    icon: FileCode2,
    minHeight: 4,
    defaultHeight: 6,
    category: 'config',
    closeable: true,
    docsUrl: 'https://docs.sourceprep.io/mcp/ides',
  },
  {
    id: 'status',
    title: 'Knowledge Status',
    description: 'Health and freshness of your codebase knowledge — chunks indexed, embedding model, last build, stale-file count.',
    icon: Database,
    minHeight: 3,
    defaultHeight: 4,
    category: 'status',
    closeable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#index-status',
  },
  {
    id: 'build',
    title: 'Rebuild Knowledge',
    description: 'Manually rebuild the project knowledge. The file watcher handles most rebuilds automatically; this is for cases the watcher misses (branch switches, config changes, troubleshooting).',
    icon: Hammer,
    minHeight: 3,
    defaultHeight: 4,
    category: 'status',
    closeable: true,
    docsUrl: 'https://docs.sourceprep.io/how-it-works/indexing',
    devOnly: true,
  },
  {
    // Phase 74: Sunset — AI Gateway summary card used manually-constructed state
    // that drifted from real pipeline status. The sidebar AI Gateway widget is now
    // the sole live view; full settings open via its expand button → panelDetails.
    id: 'llm-status',
    title: 'AI Gateway',
    description: 'Connection status for local (Ollama) and cloud (OpenAI/Anthropic) models.',
    icon: Settings2,
    minHeight: 4,
    defaultHeight: 8,
    category: 'status',
    closeable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#key-panels',
    devOnly: true,
  },
  {
    id: 'search',
    title: 'Search',
    description: 'Semantic search across your codebase knowledge — find code, docs, and plans by meaning.',
    icon: Search,
    minHeight: 5,
    defaultHeight: 7,
    category: 'search',
    closeable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#search-context',
  },
  {
    id: 'context-options',
    title: 'Context Assembler',
    description: 'Configure and assemble the context prompt from search results.',
    icon: SlidersHorizontal,
    minHeight: 3,
    defaultHeight: 8,
    category: 'context',
    closeable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#search-context',
  },
  {
    id: 'results',
    title: 'Retrieved Context',
    description: 'Chunks of code and text retrieved from your codebase knowledge.',
    icon: List,
    minHeight: 6,
    defaultHeight: 10,
    category: 'search',
    closeable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#search-context',
  },
  {
    id: 'context-output',
    title: 'Prompt Buffer',
    description: 'The final assembled context, ready to be copied to your LLM.',
    icon: FileText,
    minHeight: 6,
    defaultHeight: 10,
    category: 'context',
    closeable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#search-context',
  },
  {
    id: 'file-tree',
    title: 'Knowledge Scope',
    description: 'Pick which files belong in your codebase knowledge. Boost or suppress folders with per-path weights, or exclude them from the structural graph entirely.',
    icon: FolderTree,
    minHeight: 6,
    defaultHeight: 10,
    category: 'search',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/guides/knowledge-scope',
  },
  {
    id: 'trace',
    title: 'Code Graph Explorer',
    description: 'Navigate the complete web of relationships (imports, calls, definitions) across the codebase.',
    icon: GitBranch,
    minHeight: 6,
    defaultHeight: 10,
    category: 'search',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#code-graph-coverage',
  },
  // trace-coverage (Graph Status) removed — consolidated into graph-structure (Graph Scope)
  {
    id: 'deep-analysis',
    title: 'Deep Analysis',
    description: 'LLM-powered validation of code summaries. Configure budgets, run manually, and monitor progress.',
    icon: Brain,
    minHeight: 4,
    defaultHeight: 8,
    category: 'config',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#pipeline',
  },
  {
    id: 'trace-pipeline',
    title: 'Graph Enrichment',
    description: 'The 15-stage enrichment pipeline: Sync (Structural → Inferred Edges → Catalogue → Validation → Knowledge) → Enrich (Deep Reasoning → Group Reasoning → Module Synthesis → Deepening → Deep Knowledge) → Finalize (Atlas → Rules → Concepts → Audit → Antibodies). Hover each stage for its epistemological role.',
    icon: Brain,
    minHeight: 6,
    defaultHeight: 12,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/how-it-works/graph-enrichment',
  },
  {
    id: 'graph-structure',
    title: 'Graph Scope',
    description: 'Pipeline file inventory: the Queue of pending/stale work and the active exclude Patterns.',
    icon: Database,
    minHeight: 6,
    defaultHeight: 10,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/guides/knowledge-scope',
  },
  // graph-engine (Graph Engine) removed — consolidated into trace-pipeline (Graph Enrichment)
  {
    id: 'index-health',
    title: 'Knowledge Health',
    description: 'Health score, freshness, staleness, and coverage metrics for your codebase knowledge.',
    icon: HeartPulse,
    minHeight: 4,
    defaultHeight: 6,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#index-status',
  },
  {
    id: 'atlas',
    title: 'Codebase Atlas',
    description: 'Architectural overview of your codebase. Used for pre-retrieval routing — scoping queries to the right subsystem before search begins.',
    icon: Map,
    minHeight: 4,
    defaultHeight: 6,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/how-it-works/code-graph',
  },
  {
    id: 'token-budget',
    title: 'Token Budget',
    description: 'Track deep reasoning and module synthesis token usage against your configured budget window.',
    icon: Coins,
    minHeight: 3,
    defaultHeight: 5,
    category: 'config',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/how-it-works/compression',
  },
  {
    id: 'audit',
    title: 'Codebase Audit',
    description: 'Autonomous health analysis: architecture findings, tech debt, test coverage gaps, dead code, and actionable recommendations — all from the trace graph.',
    icon: ClipboardCheck,
    minHeight: 6,
    defaultHeight: 10,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/guides/codebase-audit',
  },
  {
    // Phase 65: Sunset — functionality merged into Opportunities panel
    id: 'spaghetti',
    title: 'Spaghetti Finder',
    description: 'Ranked list of files by refactor urgency. Combines line count, coupling, symbol density, tech debt, and epistemic confidence into a composite score.',
    icon: AlertTriangle,
    minHeight: 6,
    defaultHeight: 10,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/guides/codebase-audit',
    devOnly: true,
  },
  {
    id: 'activity-heatmap',
    title: 'Knowledge Activity',
    description: 'GitHub-style heatmap showing knowledge-building activity (embeddings + graph) over time.',
    icon: Flame,
    minHeight: 4,
    defaultHeight: 6,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/dashboard#index-status',
  },
  {
    // Phase 65: Sunset — future revisit with roadmap_layout_concept.png
    id: 'goalposts',
    title: 'Goalposts',
    description: 'AI-generated project milestones: forward-looking proposals based on codebase analysis, audit findings, and product intent.',
    icon: Target,
    minHeight: 6,
    defaultHeight: 10,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/guides/codebase-audit',
    devOnly: true,
  },
  {
    // Phase 65: Sunset — functionality merged into Opportunities panel
    id: 'health_scanner',
    title: 'Health Scanner',
    description: 'Unified codebase diagnostics: audit findings, file refactoring scores, architecture issues, and tech debt — all in one view with AI handoff.',
    icon: HeartPulse,
    minHeight: 6,
    defaultHeight: 10,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/guides/codebase-audit',
    devOnly: true,
  },
  {
    // Phase 65: Sunset — functionality merged into Opportunities panel
    id: 'advisor',
    title: 'Advisor',
    description: 'AI-powered design proposals: proactive architecture, feature, and tech debt recommendations with Copy-for-AI handoff.',
    icon: Compass,
    minHeight: 6,
    defaultHeight: 10,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/guides/model-advisor',
    devOnly: true,
  },
  {
    id: 'roadmap',
    title: 'Roadmap',
    description: 'Visual project timeline: track completed, active, planned, and proposed milestones. AI-generated proposals, TODO scanning, and manual nodes.',
    icon: Map,
    minHeight: 12,
    defaultHeight: 16,
    category: 'status',
    closeable: true,
    resizable: true,
    fullWidth: true,
    docsUrl: 'https://docs.sourceprep.io/guides/codebase-audit',
    devOnly: true,
  },
  {
    id: 'opportunities',
    title: 'Opportunities',
    description: 'Unified codebase improvement opportunities: architecture issues, tech debt, naming problems, and AI-driven recommendations. Export as SARIF, JSON, CSV, or paste-ready AI prompts.',
    icon: Lightbulb,
    minHeight: 6,
    defaultHeight: 10,
    category: 'status',
    closeable: true,
    resizable: true,
    docsUrl: 'https://docs.sourceprep.io/guides/codebase-audit',
    devOnly: true,
  },
  {
    id: 'agent-ops',
    title: 'Agent Operations',
    description: 'Configure SourcePrep agent engines (HR, Researcher, Custodian), Paperclip connection, and push settings.',
    icon: Bot,
    minHeight: 4,
    defaultHeight: 6,
    category: 'config',
    closeable: true,
    resizable: true,
  },
  {
    id: 'architecture',
    title: 'Architecture',
    description: 'Interactive architecture diagram: visualize modules, dependencies, and annotations. Drill down from system overview to individual files.',
    icon: Network,
    minHeight: 6,
    defaultHeight: 8,
    category: 'context',
    closeable: true,
    resizable: true,
    fullWidth: true,
  },
  {
    id: 'concepts',
    title: 'Concepts',
    description: 'High-level codebase understanding: business rationale, design decisions, domain knowledge, and architectural intent. AI-seeded, user-curated.',
    icon: Brain,
    minHeight: 6,
    defaultHeight: 8,
    category: 'context',
    closeable: true,
    resizable: true,
  },
];

/**
 * Get panel definition by ID
 */
export function getPanelDefinition(id: string): PanelDefinition | undefined {
  return PANEL_REGISTRY.find((p) => p.id === id);
}

/**
 * Get panels grouped by category
 */
export function getPanelsByCategory(showDevPanels = false): Record<string, PanelDefinition[]> {
  const grouped: Record<string, PanelDefinition[]> = {};
  for (const panel of PANEL_REGISTRY) {
    if (panel.devOnly && !showDevPanels) continue;
    if (!grouped[panel.category]) {
      grouped[panel.category] = [];
    }
    grouped[panel.category].push(panel);
  }
  return grouped;
}
